import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>WELCOME NEXT JS CODEVOLUTION</h2>
      <Link href='/docs'>Docs Route Dynamic</Link><br/>
      <Link href='/users'>Data Users</Link><br/>
      <Link href='/post'>Data Post</Link><br/>
      <Link href='/products'>Data Products</Link><br/>
      <Link href='/news'>Data News</Link>
    </div>
  )
}
